# Generated by Django 3.1.5 on 2021-02-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0002_auto_20210131_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='masking',
            name='GI_A',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='masking',
            name='GI',
            field=models.IntegerField(null=True),
        ),
    ]
