# Generated by Django 3.1.5 on 2021-02-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0003_auto_20210214_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masking',
            name='GI_A',
        ),
    ]
