# Generated by Django 3.1.5 on 2021-02-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0004_remove_masking_gi_a'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masking',
            options={'ordering': ['-GI']},
        ),
        migrations.AddField(
            model_name='masking',
            name='GI_A',
            field=models.CharField(default='', max_length=10),
        ),
    ]
